# Generated by Django 6.0 on 2026-01-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='breed',
            new_name='brand',
        ),
    ]
