# Generated by Django 6.0 on 2026-01-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_breed_grocery_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/static/uploads/'),
        ),
    ]
