# Generated by Django 6.0 on 2026-02-01 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_grocery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.grocery')),
            ],
        ),
    ]
