# Generated by Django 6.0 on 2026-02-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_bought'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bought',
            old_name='Grocery',
            new_name='grocery',
        ),
    ]
