# Generated by Django 6.0 on 2026-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_grocery_bought_grocery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='grocery',
            name='coupons',
            field=models.ManyToManyField(to='main_app.coupon'),
        ),
    ]
